### ISSUE TITLE
edns() ,  what is this keyword mean and do ??

### ISSUE THREAD

**Issue by ghost** [prash071/Soft-Computing-Algorithms#1]
Hi, 

I have tried too implement the ABC algorithm , but am getting problem with 👍 

system_cost(i,1) = 0.0000265 * edns(Foods(i,:))*8760 + system_cost(i,1);

**the matlab softare that iam using 2015b ?? and it does not recognize edns()**

**Comment by prash071** [comment]
Hi,
edns is not related to ABC algorithm. It is related to reliability evaluation in power systems.
